apiVersion: v2
name: huly
description: Helm chart for Huly, an open-source project management platform
type: application
version: 0.1.9
appVersion: "v0.7.242"
home: https://huly.io
sources:
  - https://github.com/hcengineering/huly-platform
  - https://github.com/Kubedoll-Heavy-Industries/charts
keywords:
  - huly
  - project-management
  - collaboration
maintainers:
  - name: Kubedoll Heavy Industries
