apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "terraria-tshock.fullname" . }}-serverfiles
  labels:
    {{- include "terraria-tshock.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
