{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "huly.fullname" . }}-secret
  labels:
    {{- include "huly.labels" . | nindent 4 }}
type: Opaque
stringData:
  SERVER_SECRET: {{ required "serverSecret is required" .Values.serverSecret | quote }}
  SECRET: {{ .Values.serverSecret | quote }}
  STORAGE_CONFIG: {{ include "huly.storageConfig" . | quote }}
{{- end }}
