# Modified by Kubedoll Heavy Industries from bjw-s-labs app-template 5.0.1.
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Renamed the upstream app-template chart for Geodesa first-party workloads.
  geodesa.ai/upstream-archive-sha256: e99ebe581c41a38e1fa282bf53d4306b5cba01a27f89543583dc0817b8fa6558
  geodesa.ai/upstream-commit: eea11eae60170b61485cc14314a6bf20f42c79e4
  geodesa.ai/upstream-oci-digest: sha256:70a7cb6766eb468068c2c1700c8450253070dc671a9fbbd1a6346a66545e2b2b
  geodesa.ai/upstream-version: 5.0.1
apiVersion: v2
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
description: A minimally changed bjw-s app-template fork for Geodesa first-party applications.
kubeVersion: ">=1.28.0-0"
maintainers:
  - name: Kubedoll Heavy Industries
name: geodesa-app
sources:
  - https://github.com/bjw-s-labs/helm-charts/tree/app-template-5.0.1/charts/other/app-template
  - https://github.com/Kubedoll-Heavy-Industries/charts
type: application
version: 5.0.1-kdhi.1
